---
name: Run all tests, including slow tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  slow-tests:
    name: Run slow tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: install code
        env:
          MAVEN_CONFIG: "-B -fae"
        run: |
          make install-fast

      - name: run slow tests
        env:
          MAVEN_CONFIG: "-B -fae"
        run: |
          make run-slow-tests

  slow-tests-locale:
    name: Run slow tests with different timezone and locale
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: install code
        env:
          MAVEN_CONFIG: "-B -fae"
        run: |
          make install-fast

      - name: run slow tests
        env:
          MAVEN_CONFIG: "-B -fae -Djdbi.test.timezone=Asia/Colombo -Djdbi.test.language=tr -Djdbi.test.region=TR"
        run: |
          make run-slow-tests
